import { ComponentType } from 'react';

/**
 * Core configuration for a coding agent plugin
 */
export interface PluginConfig {
  name: string;
  version: string;
  description: string;
  author: string;
  icon?: string;
  supportedModels: string[];
  defaultModel: string;
  requiresApiKey: boolean;
  uiComponent: UiComponentType;
  capabilities: PluginCapabilities;
}

/**
 * Type of UI component the plugin uses
 */
export type UiComponentType = 'tmux' | 'custom' | 'webview' | 'iframe';

/**
 * Capabilities that a plugin supports
 */
export interface PluginCapabilities {
  fileOperations: boolean;
  terminalAccess: boolean;
  gitOperations: boolean;
  webSearch: boolean;
  codeExecution: boolean;
  customTools: string[];
}

/**
 * Plugin metadata with frontend-specific properties
 */
export interface CodingAgentPlugin extends PluginConfig {
  id: string;

  // UI Component configuration
  customRenderer?: ComponentType<PluginUIProps>;
  customStyles?: string;

  // UI Configuration
  uiConfig?: {
    showTerminal?: boolean;
    showChat?: boolean;
    showFileTree?: boolean;
    customPanels?: PanelConfig[];
  };

  // Terminal command generator (for tmux-based plugins)
  terminalCommand?: (port: number, sessionId?: string) => string;

  // API endpoint configuration
  apiEndpoint?: string;
  apiVersion?: string;
}

/**
 * Props passed to custom plugin UI components
 */
export interface PluginUIProps {
  plugin: CodingAgentPlugin;
  session: AgentSession | null;
  server: AgentServer | null;
  onCommand: (command: string) => void;
  onToolApproval?: (toolUse: ToolUse, approved: boolean) => void;
  config: Record<string, any>;
}

/**
 * Interface for plugins to integrate with Sensei
 * Plugins should call senseiService.addAgentRecommendation()
 * when they have actionable responses to share
 */
export interface SenseiIntegration {
  /**
   * Add an agent response to Sensei as a recommendation
   * @param serverId The server ID (e.g., 'opencode-4097')
   * @param sessionId The session ID
   * @param userInput What the user asked
   * @param agentResponse The agent's response
   * @param agentName Name of the agent (e.g., 'claude-code', 'copilot', 'cursor')
   * @param confidence Confidence level 0-1 (default: 0.95 for AI agents)
   */
  addRecommendation(
    serverId: string,
    sessionId: string,
    userInput: string,
    agentResponse: string,
    agentName: string,
    confidence?: number
  ): void;
}

/**
 * Configuration for custom panels in plugin UI
 */
export interface PanelConfig {
  id: string;
  title: string;
  position: 'left' | 'right' | 'bottom' | 'top';
  defaultSize?: number;
  resizable?: boolean;
  collapsible?: boolean;
}

/**
 * Agent server information
 */
export interface AgentServer {
  id: string;
  pluginId: string;
  host: string;
  port: number;
  status: ServerStatus;
  model: string;
  workingDir: string;
  createdAt: string;
  metadata: Record<string, any>;
}

/**
 * Server status
 */
export type ServerStatus = 'starting' | 'running' | 'stopped' | 'error';

/**
 * A session with a coding agent
 */
export interface AgentSession {
  id: string;
  serverId: string;
  pluginId: string;
  createdAt: string;
  status: SessionStatus;
  metadata: Record<string, any>;
}

/**
 * Session status
 */
export type SessionStatus = 'active' | 'idle' | 'working' | 'completed' | 'failed';

/**
 * Response from an agent
 */
export interface AgentResponse {
  sessionId: string;
  content: string;
  responseType: ResponseType;
  metadata: Record<string, any>;
}

/**
 * Type of response from the agent
 */
export type ResponseType = 'message' | 'code' | 'tool_use' | 'error' | 'progress' | 'artifact';

/**
 * Tool use by an agent
 */
export interface ToolUse {
  toolName: string;
  parameters: Record<string, any>;
  result?: string;
  status: ToolStatus;
}

/**
 * Status of a tool invocation
 */
export type ToolStatus = 'pending' | 'running' | 'completed' | 'failed' | 'requires_approval';

/**
 * Artifact generated by an agent
 */
export interface Artifact {
  id: string;
  type: 'file' | 'code' | 'documentation' | 'other';
  name: string;
  content: string;
  language?: string;
  path?: string;
  version: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * Message in a conversation with an agent
 */
export interface ConversationMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  artifacts?: Artifact[];
  toolUses?: ToolUse[];
  metadata?: Record<string, any>;
}

/**
 * Plugin settings that can be configured by the user
 */
export interface PluginSettings {
  pluginId: string;
  apiKey?: string;
  model?: string;
  temperature?: number;
  maxTokens?: number;
  customEndpoint?: string;
  additionalSettings?: Record<string, any>;
}